### PR TITLE
Fix serialization of expandable fields

### LINKED ISSUE #422: Error when deserializing a Charge object
I'm using stripe-java 5.23.0, with Java 1.8.

I have a webhook setup up for the "charge.succeeded" event. The method looks like this.

     @CrossOrigin
     @RequestMapping(path = "/update", method = {RequestMethod.POST}, consumes = MimeTypeUtils.APPLICATION_JSON_VALUE, produces = MimeTypeUtils.APPLICATION_JSON_VALUE)
     public ResponseEntity<MyResponse> update(@RequestBody(required = false) String json) {
        ResponseEntity<MyResponse> re;
       
        Event stripeEvent = Event.GSON.fromJson(json, Event.class);
        logger.info("Endpoint reached with json:{}", json);
        String eventObjJson = stripeEvent.getData().getObject().toJson();
        logger.info("event -> getData -> getObject -> toJson:{}", eventObjJson);

        Charge charge =  Event.GSON.fromJson(stripeEvent.getData().getObject().toJson(), Charge.class);
     }

When testing a successful charge the call fails on the last line, when deserializing the charge object.

Here's the log output of the first log line (the entire event json):
       
    {
        "created": 1326853478,
        "livemode": false,
        "id": "evt_00000000000000",
        "type": "charge.succeeded",
        "object": "event",
        "request": null,
        "pending_webhooks": 1,
        "api_version": "2017-08-15",
        "data": {
        "object": {
            "id": "ch_00000000000000",
            "object": "charge",
            "amount": 4900,
            "amount_refunded": 0,
            "application": null,
            "application_fee": null,
            "balance_transaction": "txn_00000000000000",
            "captured": true,
            "created": 1510158112,
            "currency": "usd",
            "customer": "cus_00000000000000",
            "description": "Description",
            "destination": null,
            "dispute": null,
            "failure_code": null,
            "failure_message": null,
            "fraud_details": {
            },
            "invoice": null,
            "livemode": false,
            "metadata": {
                "responseId": "R_2EtnlHOgqTgV2Zt"
            },
            "on_behalf_of": null,
            "order": null,
            "outcome": {
                "network_status": "approved_by_network",
                "reason": null,
                "risk_level": "normal",
                "seller_message": "Payment complete.",
                "type": "authorized"
            },
            "paid": true,
            "receipt_email": "fdjnfnf@gggg.com",
            "receipt_number": null,
            "refunded": false,
            "refunds": {
                "object": "list",
                "data": [
    
                ],
                "has_more": false,
                "total_count": 0,
                "url": "/v1/charges/ch_1BLwJILN9LSzPoXKTdMF6RiR/refunds"
            },
            "review": null,
            "shipping": null,
            "source": {
                "id": "card_00000000000000",
                "object": "card",
                "address_city": "fhjdfhj",
                "address_country": "United States",
                "address_line1": "fdhdfjhFH",
                "address_line1_check": "pass",
                "address_line2": null,
                "address_state": "NY",
                "address_zip": "12345",
                "address_zip_check": "pass",
                "brand": "Visa",
                "country": "US",
                "customer": "cus_00000000000000",
                "cvc_check": "pass",
                "dynamic_last4": null,
                "exp_month": 11,
                "exp_year": 2029,
                "fingerprint": "wqEb6wBZozp3h9Lp",
                "funding": "credit",
                "last4": "4242",
                "metadata": {
                },
                "name": "name",
                "tokenization_method": null
            },
            "source_transfer": null,
            "statement_descriptor": null,
            "status": "succeeded",
            "transfer_group": null
        }
    }
    }

The exception I get from the last line:
java.lang.NullPointerException: null
	at com.stripe.model.BalanceTransactionDeserializer.deserialize(BalanceTransactionDeserializer.java:57) ~[stripe-java-5.23.0.jar!/:?]
	at com.stripe.model.BalanceTransactionDeserializer.deserialize(BalanceTransactionDeserializer.java:17) ~[stripe-java-5.23.0.jar!/:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.1.jar!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.1.jar!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[gson-2.8.1.jar!/:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[gson-2.8.1.jar!/:?]
	at com.stripe.model.ExpandableFieldDeserializer.deserialize(ExpandableFieldDeserializer.java:36) ~[stripe-java-5.23.0.jar!/:?]
	at com.stripe.model.ExpandableFieldDeserializer.deserialize(ExpandableFieldDeserializer.java:8) ~[stripe-java-5.23.0.jar!/:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.1.jar!/:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) ~[gson-2.8.1.jar!/:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) ~[gson-2.8.1.jar!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.1.jar!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:852) ~[gson-2.8.1.jar!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:801) ~[gson-2.8.1.jar!/:?]
	at com.google.gson.Gson.fromJson(Gson.java:773) ~[gson-2.8.1.jar!/:?]
	at com.tapd.um.rest.controller.Stripe.updateToInReview(Stripe.java:54) [classes!/:?]
	at sun.reflect.GeneratedMethodAccessor143.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) [spring-web-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) [spring-web-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97) [spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) [spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) [spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) [spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967) [spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) [spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) [spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872) [spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) [javax.servlet-api-3.1.0.jar!/:3.1.0]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) [spring-webmvc-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet-api-3.1.0.jar!/:3.1.0]
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) [spring-web-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105) [spring-web-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81) [spring-web-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) [spring-web-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.10.RELEASE.jar!/:4.3.10.RELEASE]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) [undertow-core-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) [undertow-core-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) [undertow-core-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104) [undertow-servlet-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:326) [undertow-core-1.4.18.Final.jar!/:1.4.18.Final]
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:812) [undertow-core-1.4.18.Final.jar!/:1.4.18.Final]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

Since I had almost no need for anything besides the meta data - I ended up writing my own minimalistic class just for the id and meta data - but it seems like there's something wrong with the deserialization here.

EDIT: code formatting

### PR DESCRIPTION
**Pull request by ob-stripe**
r? @brandur-stripe 
cc @stripe/api-libraries 

Fixes #422.

Our serialization logic did not take expandable fields into accounts, so all expandable fields were serialized as:

```json
{
  "id": "resource_id",
  "expanded_object": null
}
```

This PR introduces a custom `ExpandableFieldSerializer` to correctly serialize expandable fields.

While working on this, I also noticed another issue. We use two different `Gson` instances in the library:
- `StripeObject.PRETTY_PRINT_GSON` is used to serialize Stripe object
- `APIResource.GSON` is used to deserialize resources returned by the API

However, we were incorrectly using `StripeObject.PRETTY_PRINT_GSON` instead of `APIResource.GSON` in a few places. This is now fixed. I have left the two custom deserializers that were registered in `StripeObject.PRETTY_PRINT_GSON` to avoid a breaking change, but we should remove them in the next major release.

### CODE REVIEW

File: src/main/java/com/stripe/net/APIResource.java [hunk 1]
```diff
@@ -50,18 +50,18 @@ public static void setStripeResponseGetter(StripeResponseGetter srg) {
...
-			.registerTypeAdapter(StripeRawJsonObject.class, new StripeRawJsonObjectDeserializer())
-			.registerTypeAdapter(BalanceTransaction.class, new BalanceTransactionDeserializer())
-			.registerTypeAdapter(Dispute.class, new DisputeDataDeserializer())
+			.registerTypeAdapter(OrderItem.class, new OrderItemDeserializer())
 			.registerTypeAdapter(Source.class, new SourceTypeDataDeserializer<Source>())
 			.registerTypeAdapter(SourceTransaction.class, new SourceTypeDataDeserializer<SourceTransaction>())
-			.registerTypeAdapter(OrderItem.class, new OrderItemDeserializer())
-			.registerTypeAdapter(ExpandableField.class, new ExpandableFieldDeserializer())
-			.registerTypeAdapter(EphemeralKey.class, new EphemeralKeyDeserializer())
+			.registerTypeAdapter(StripeRawJsonObject.class, new StripeRawJsonObjectDeserializer())
```
Comment (brandur-stripe) [inline src/main/java/com/stripe/net/APIResource.java]: Thanks for bringing some order to this list :)

File: src/test/java/com/stripe/model/ExpandableFieldSerializerTest.java [hunk 2]
```diff
@@ -0,0 +1,46 @@
...
+    public void serializeExpanded() throws IOException {
+        TestNestedObject nested = new TestNestedObject();
+        nested.id = "id_expanded";
+        nested.bar = 42;
+        TestTopLevelObject object = new TestTopLevelObject();
+        object.nested = new ExpandableField<TestNestedObject>(nested.id, nested);
+
+        String expected = "{\n  \"nested\": {\n    \"id\": \"id_expanded\",\n    \"bar\": 42\n  }\n}";
+        assertEquals(expected, object.toJson());
+    }
```
Comment (brandur-stripe) [inline src/test/java/com/stripe/model/ExpandableFieldSerializerTest.java]: Amazing job adding these additional test cases as well! Really nice to have these in place to help prevent future regressions.

**Comment by brandur-stripe** [comment]
Thanks OB! Looks great.

> However, we were incorrectly using StripeObject.PRETTY_PRINT_GSON instead of APIResource.GSON in a few places. This is now fixed. I have left the two custom deserializers that were registered in StripeObject.PRETTY_PRINT_GSON to avoid a breaking change, but we should remove them in the next major release.

Nice catch :$ Good call leaving that TODO in there. I guess we should start grouping major version TODOs together somewhere.
